import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const northWell = localFont({
  src: "./fonts/Northwell.ttf",
  variable: "--font-northwell",
  weight: "100 900",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const tenPearl = localFont({
  src: "./fonts/tanPearl.otf",
  variable: "--font-ten-pearl",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "The Grey Wall",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon2.ico",
  },
};

const montserrat = Montserrat({ weight: "600", subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tenPearl.variable}  antialiased ${montserrat.className} ${northWell.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
